// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/todo',
        uri: Uri.parse('/todo'),
        routeBuilder: b0Builder,
      ),
    ];

const routePaths = (
  path: '/',
  todo: '/todo',
);
